---
title: "NYC Restaurant Insepctions Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)

data("rest_inspec")
```

```{r, include=FALSE}
plotly_box = rest_inspec %>%
  filter(
    grade == "A", boro != "Missing")

plotly_bar = rest_inspec %>% 
  filter(grade == "A", boro == "MANHATTAN", cuisine_description != "Not Listed/Not Applicable") %>% 
  count(cuisine_description) %>% 
  filter(n > 1000) %>% 
  mutate(
    cuisine_description = recode(cuisine_description, "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin")
  ) 

plotly_scatter = rest_inspec %>% 
  filter(
    boro == "MANHATTAN", str_detect(cuisine_description, "[Cc][Hh][Ii][Nn][Ee][Ss][Ee]"), grade != "Not Yet Graded") 
```


Column {data-width=650}
-------------------------------------------------------------------------

### Chart A

```{r}
plotly_box %>%
  mutate(
    text_label = str_c("Score: ", score)
  ) %>% 
  plot_ly(
    y = ~score, color = ~boro,
    type = "box", mode = "markers",
    alpha = .5, text = ~text_label
  ) %>% 
  layout(
    title = "The distribution of score by boro",
    xaxis = list(title = "Boro"),
    yaxis = list(title = "Score"),
    legend = list(title = list(text = '<b> Boro </b>'), y = 0.5))

```



Column {data-width=350}
-------------------------------------------------------------------------


### Chart B

```{r}

plotly_bar %>% 
mutate(
    text_label = str_c("Number: ", n),
    cuisine_description = fct_reorder(cuisine_description, n)
  ) %>% 
  plot_ly(
    x = ~cuisine_description, y = ~n, color = ~cuisine_description,
    type = "bar", mode = "markers",
    alpha = .5, text = ~text_label
  ) %>% 
  layout(
    title = "The number of A grade restaurant in Manhattan",
    xaxis = list(title = "Cuisine Type"),
    yaxis = list(title = "Count"),
    legend = list(title = list(text = '<b> Cuisine Type </b>'), y = 0.5))
```


### Chart C

```{r}

plotly_scatter %>% 
  mutate(
    text_label = str_c("Grade: ", grade, "\nScore: ", score)
  ) %>% 
  plot_ly(
    x = ~grade_date, y = ~score, color = ~grade,
    type = "scatter", mode = "markers",
    alpha = 1, text = ~text_label
  ) %>% 
  layout(
    title = "The distribution of score by grade date",
    xaxis = list(title = "Grade Date"),
    yaxis = list(title = "Score"),
    legend = list(title = list(text = '<b> Grade </b>'), y = 0.5))
```
