name: "Yingchen Xu"
output_dir: "."
navbar:
  title: "Home"
  right:
    - text: "About"
      href: about.html
    - icon: <i class="fa-solid fa-file-user"></i>
      href: ./resource/Yingchen Xu - Resume.pdf
    - icon: fa-envelope fa-lg
      href: mailto:<yx2711@cumc.columbia.edu>
    - icon: fa-github fa-lg
      href: http://github.com/yingchenx/
output:
  html_document:
    theme: flatly